apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: random-test
  namespace: kargo-playground
spec:
  metrics:
  - name: random-test
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command: [sh, -c, "sleep $((RANDOM % 21 + 10))"]
              restartPolicy: Never
          backoffLimit: 1
