apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-playground
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-playground
  namespace: kargo-playground
spec:
  promotionPolicies:
  - stageSelector:
      name: staging
    autoPromotionEnabled: true
  - stageSelector:
      name: prod-ring1
    autoPromotionEnabled: true
  - stageSelector:
      name: prod-ring2
    autoPromotionEnabled: true
