apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-playground:staging
spec:
  project: default
  source:
    repoURL: https://github.com/p8r-the-gr8/kargo-playground.git
    targetRevision: stage/staging
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: web-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
